# 보안 주의!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j7b207.p.ssafy.io:3306/newstudy?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: newstudy
    password: dhdwhf7xladb!

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher  # swagger ?? ? ? ?? ?? ?????

  #redis
  #spring.redis.host= 172.17.0.3ss
  redis:
    host: 127.0.0.1
    port: 6379

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




  # for SPA
 # spring.resources.static-locations=classpath:/dist/
 # spa.default-file=/dist/index.html
spa:
  default-file: /dist/index.html
 # spring.mvc.throw-exception-if-no-handler-found=true
 # spring.resources.add-mappings=false

#  mail:
#    host: smtp.naver.com
#    port: 465
#    username:
#    password:
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
  profiles:
    include: API-KEY

# Swagger
#springfox:
#  documentation:
#    swagger:
#      use-model-v3: false


# jwt
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
# unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days
  expiration: 1296000000

server:
  servlet:
    context-path: /api
  encoding:
    charset: UTF-8
  port: 8080

# mybatis setting
mybatis:
  type-aliases-package: com.ssafy.newstudy.model.dto
  mapper-locations: classpath:/mappers/*Mapper.xml